version: '3.4'

services:
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
      args:
        - --no-cache
    volumes:
      - ./api:/app:rw
    env_file:
      - .api.env
    restart: always

  front:
    build:
      context: ./front/
      dockerfile: ./Dockerfile
      args:
        - --no-cache
    volumes:
      - ./front/build:/app:rw
    restart: always

  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql:rw

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # General nginx template
      - ./nginx/api.conf:/etc/nginx/api.conf # api template
      - ./nginx/front.conf:/etc/nginx/front.conf # front template
    ports:
      - 80:80
      - 443:443
    command: sh -c "nginx -g 'daemon off;'"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 50M
