version: '3.4'

services:
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
      args:
        - --no-cache
    volumes:
      - ./api:/app:rw
    env_file:
      - .api.env
    restart: always

  front:
    build:
      context: ./front/
      dockerfile: ./Dockerfile
      args:
        - --no-cache
    volumes:
      - ./front/build:/app:rw
    restart: always

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # General nginx template
      - ./nginx/api.conf:/etc/nginx/api.conf # api template
      - ./nginx/front.conf:/etc/nginx/front.conf # front template
    ports:
      - 80:80
      - 443:443
    command: sh -c "nginx -g 'daemon off;'"

  # adminer:
  #   image: adminer:4.7.8
  #   ports:
  #     - 8080:8080

volumes:
  db-data: {}
